# file: calibration_config.yaml
general:
  strategy: 
      # Type of strategy, currently supported is estimation
      type: estimation
      # defaults to dds (currently, the only supported algorithm)
      algorithm: "dds"

  # Enable model runtime logging (captures standard out and error and writes to file)
  # logs will be written to <model.type>.log when enabled
  # defaults to False, which sends all output to /dev/null
  log: True

  start_iteration: 0
  # The total number of search iterations to run
  iterations: 2
  random_seed: 444
  workdir: ./

  #plugins:
  #   - "ngen_cal_user_plugins.ngen_cal_save_iteration_output_plugin.SaveValidation"  # saves ngen *.csv to "output_validation" directory
  #   - "ngen_cal_user_plugins.ngen_cal_save_sim_obs_plugin.SaveValidation"  # saves ngen *.csv to "output_validation" directory
     
# Define parameters to calibrate, their bounds, and initial values.
cfe_params: &cfe_params
  - 
      name: maxsmc
      min: 0.2
      max: 1.0
      init: 0.439
  - 
      name: satdk
      min: 0.0
      max: 0.000726
      init: 3.38e-06
  - 
      name: slope
      min: 0.0
      max: 1.0
      init: 0.01
  - 
      name: expon
      min: 1.0
      max: 8.0
      init: 6.0
  -     
      name: b
      min: 0.0 
      max: 16
      init: 4.05
  -     
      name: satpsi
      min: 0.036
      max: 0.995
      init: 0.355
  -     
      name: max_gw_storage
      min: 0.01
      max: 0.2 
      init: 0.05
  -     
      name: Cgw 
      min: 1.6266e-06
      max: 0.00016266
      init: 1.6266e-05
  -     
      name: Kn
      min: 0.0 
      max: 1.0 
      init: 0.03
  -     
      name: Klf 
      min: 0.0 
      max: 1.0 
      init: 0.01
  -       
      name: Kinf_nash_surface
      min: 1.0e-06
      max: 0.005
      init: 0.002
  - 
      name: retention_depth_nash_surface
      min: 0.0 
      max: 0.02
      init: 0.001
  - 
      name: refkdt
      min: 0.1
      max: 4.0
      init: 3.0

##nom_parameters: &nom_parameters
nom_params: &nom_params
  - 
      name: MFSNO # fractional snow covered area (FSNO) curve parameter (pseduo multiplier)
      min: 0.5
      max: 4.0 
      init: 2.0 
  - 
      name: SCAMAX # maximum fractional snow-covered area
      min: 0.7 
      max: 1.0 
      init: 0.9 
  - 
      name: RSURF_SNOW # surface resistence for snow [s/m]
      min: 0.136 
      max: 100.0
      init: 50.0
  -
      name: HVT # canopy top height (m)
      min: 0.0 
      max: 20.0
      init: 1.0 
#  - 
#      name: RSURF_EXP #Exponent in the resistance equation for soil evaporation
#      min: 1.0
#      max: 6.0
#      init: 5.0
  - 
      name: CWP # canopy wind absorption coefficient (formerly CWPVT) (multiplier)
      # values below derived as absolute values from param tables
      min: 0.09
      max: 0.36 
      init: 0.18 
  - 
      name: VCMX25 # maximum rate of carboxylation at 25c (umol co2/m**2/s) (multiplier)
      # values below derived as absolute values from param tables
      min: 24 
      max: 112
      init: 52.2
  - 
      name: MP # slope of conductance-to-photosynthesis relationship (multiplier)
      # values below derived as absolute values from param tables
      min: 3.6 
      max: 12.6
      init: 9.0 

# Model specific configuration
model:
    type: ngen
    # NOTE: you may need to adjust this to the location of your NextGen installation
    # A binary in $PATH or a qualified path to the binary to run
    binary: "./ngen/cmake_build/ngen"
    realization: ./realization.json
    # Required path to catchment hydrofabirc file
    hydrofabric: ./Gage_1022500.gpkg
    eval_feature: wb-3550
    # Each catchment upstream of observable nexus gets its own permuted parameter space, evaluates at one observable nexus 
    strategy: uniform
    params: 
        CFE: *cfe_params
        NoahOWP: *nom_params 

    eval_params:
      # choices are "kling_gupta", "nnse", "custom", "single_peak", "volume"
      objective: "kling_gupta"
    plugins:
      - "ngen_cal_user_plugins.ngen_cal_save_subcat_output_plugin.SaveData" # saves cat_*.csv or nex-*.csv to "output_iteration" directory
      - "ngen_cal_user_plugins.ngen_cal_save_sim_obs_plugin.SaveData"          # saves simulated and observed discharge at the outlet
      - "ngen_cal_user_plugins.metrics.ComputeMetrics"
